name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-3.26
          - ember-3.27-beta.1
          - ember-3.28

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
